### ISSUE TITLE
IsPlaying bool not working properly if using youtube-dl and playing online file

### ISSUE THREAD

**Issue by premingiet** [hudec117/Mpv.NET.lib#7]
As online files buffer too, so most of time isplaying gives me wrong boolean value.
 i am actually changing the "play pause" button image and if media is buffering and i click the play-pause button, so based on IsPlaying value, it changes the image.

is there any event i can subscribe to, like media is buffering or frame is rendering or something like that ?

**Comment by hudec117** [comment]
Hello @premingiet,

Currently, there is no feature to support this.

Looking at mpv.io documentation, there exist several properties which I believe would allow the detection of "buffering". I will experiment with this and get back to you. e.g. https://mpv.io/manual/stable/#command-interface-paused-for-cache

**Comment by premingiet** [comment]
okay sure

**Comment by hudec117** [comment]
While I look into this, could you confirm if the "MpvPlayer.MediaPaused" event is raised when the video buffers?

**Comment by hudec117** [comment]
I've added a `IsPausedForCache` and `CacheDuration` properties. Also added `MediaStartedBuffering` and `MediaEndedBuffering` events. 

I will release a 1.1.0-beta version in the next few days for you to test.

**Comment by premingiet** [comment]
oh just seeing your message. Great, those events will be perfect for my application. Thanks. I will be waiting for the next beta version release.

**Comment by hudec117** [comment]
Beta release available here: https://github.com/hudec117/Mpv.NET/releases/tag/v1.1.0-beta

**Comment by premingiet** [comment]
nice i will give that a go now

**Comment by hudec117** [comment]
Hello, do the events/properties work for your purposes?

**Comment by premingiet** [comment]
I was changing few other parts of my application code, by tomorrow i will test that code for player. And let you know by tomorrow.

**Comment by hudec117** [comment]
Hello, any update on this?

**Comment by hudec117** [comment]
Tested by myself, no response from premingiet. Closing.
