### ISSUE TITLE
adding new function to mpv

### ISSUE THREAD

**Issue by leichenxu** [hudec117/Mpv.NET.lib#9]
hi, i am a beginner user in c#, and i am trying to add functions for play next frame and previous frame in your mpv code, is there anyway to do it? sorry for my bad english

**Comment by hudec117** [comment]
Hello @leichenxu, yes there is.
In the mpv manual there are 2 commands, [`frame-step`](https://mpv.io/manual/stable/#command-interface-frame-step) and [`frame-back-step`](https://mpv.io/manual/stable/#command-interface-frame-step). These are not implemented at the moment but you're more than welcome to try.

Use [this ](https://github.com/hudec117/Mpv.NET/blob/master/src/Mpv.NET/Player/MpvPlayer.cs#L777 ) existing method as a point of reference on how you should implement it in the MpvPlayer class.

If you need more guidance, please reach out.

**Comment by leichenxu** [comment]
ok, thank you very much, i will try it

**Comment by leichenxu** [comment]
hi again, thank you very much, i just use mpv.Command("frame-step") and actually worked, thanks

**Comment by hudec117** [comment]
Hello @leichenxu I will be releasing 1.1.0 soon. I will implement frame stepping methods into this release.

**Comment by leichenxu** [comment]
ok, thanks for the help, and i have something to say if this may help you in your new version,

`/// <summary>
		/// Show next frame.
		/// </summary>
		public void NextFrame()
        {
            lock (mpvLock)
            {
                mpv.Command("frame-step");
                IsPlaying = false;
            }
        }
        /// <summary>
		/// Show back frame.
		/// </summary>
		public void BackFrame()
        {
            lock (mpvLock)
            {
                mpv.Command("frame-back-step");
                IsPlaying = false;
            }
        }`
i used this two simply methods for go to next and previous frame, and sometimes, this have fails, for verify why fail, i write this in your code
`public void Command(params string[] args)
		{
			Guard.AgainstDisposed(disposed, nameof(Mpv));
			Guard.AgainstNull(args, nameof(args));

			if (args.Length < 1)
				throw new ArgumentException("Missing arguments.", nameof(args));

			var argsPtr = MpvMarshal.GetComPtrForManagedUTF8StringArray(args, out IntPtr[] argsPtrs);
			if (argsPtr == IntPtr.Zero)
				throw new MpvAPIException("Failed to convert string array to pointer array.");

            //show all command used
            foreach (String s in args)
            {
                Console.WriteLine(s);
            }

            try
			{
				var error = Functions.Command(Handle, argsPtr);
				if (error != MpvError.Success)
					throw MpvAPIException.FromError(error, Functions);
			}catch (Exception e){
                //show in console when fail
                Console.WriteLine("-----------------------------------");
                Console.WriteLine("Command failed");
                Console.WriteLine(e);
                foreach (String s in args)
                {
                    Console.WriteLine(s);
                }
                Console.WriteLine("-----------------------------------");               
            }
			finally
			{
				MpvMarshal.FreeComPtrArray(argsPtrs);
				Marshal.FreeCoTaskMem(argsPtr);
			}
		}`
and i notify, that sometimes, when use NextFrame() and BackFrame(), continuously, have fail, i can not discover the reason, just for say it.

**Comment by hudec117** [comment]
@leichenxu frame stepping added in version 1.1.0
